server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.237.101:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
logging:
  level:
    root: warn
    fun.donglin: info
  file:
    name: blog/log/blog-pro.log