server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: your database url
    username: your database username
    password: your database password
logging:
  level:
    root: warn
    fun.donglin: info
  file:
    name: your log's filename