server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: your local database username
    password: your local database password
logging:
  level:
    root: info
    fun.donglin: debug
  file:
    name: blog/log/blog-dev.log