server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-remote-server-ip-or-domain-name:your-remote-database-port/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: your remote database username
    password: your remote database password
logging:
  level:
    root: warn
    fun.donglin: info
  file:
    name: blog/log/blog-pro.log